CREATE TABLE [dbo].[SCP] (
  [MATRICULE] [smallint] NOT NULL,
  [CODE_COT_PRS] [char](32) NOT NULL,
  CONSTRAINT [PK_SCP] PRIMARY KEY CLUSTERED ([MATRICULE], [CODE_COT_PRS])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SCP]
  ADD CONSTRAINT [FK_SCP_COTISATION_PERSONNEL] FOREIGN KEY ([CODE_COT_PRS]) REFERENCES [dbo].[COTISATION_PERSONNEL] ([CODE_COT_PRS])
GO

ALTER TABLE [dbo].[SCP]
  ADD CONSTRAINT [FK_SCP_SALARIE] FOREIGN KEY ([MATRICULE]) REFERENCES [dbo].[SALARIE] ([MATRICULE])
GO