CREATE TABLE [dbo].[SI] (
  [MATRICULE] [smallint] NOT NULL,
  [CODE_IDM] [char](32) NOT NULL,
  CONSTRAINT [PK_SI] PRIMARY KEY CLUSTERED ([MATRICULE], [CODE_IDM])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SI]
  ADD CONSTRAINT [FK_SI_INDEMNITES] FOREIGN KEY ([CODE_IDM]) REFERENCES [dbo].[INDEMNITES] ([CODE_IDM])
GO

ALTER TABLE [dbo].[SI]
  ADD CONSTRAINT [FK_SI_SALARIE] FOREIGN KEY ([MATRICULE]) REFERENCES [dbo].[SALARIE] ([MATRICULE])
GO