CREATE TABLE [dbo].[SE] (
  [MATRICULE] [smallint] NOT NULL,
  [N_ENTRE] [char](32) NOT NULL,
  CONSTRAINT [PK_SE] PRIMARY KEY CLUSTERED ([MATRICULE], [N_ENTRE])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[SE]
  ADD CONSTRAINT [FK_SE_ENTREPRISE] FOREIGN KEY ([N_ENTRE]) REFERENCES [dbo].[ENTREPRISE] ([N_ENTRE])
GO

ALTER TABLE [dbo].[SE]
  ADD CONSTRAINT [FK_SE_SALARIE] FOREIGN KEY ([MATRICULE]) REFERENCES [dbo].[SALARIE] ([MATRICULE])
GO