CREATE TABLE [dbo].[PRIME] (
  [CODE_PRM] [char](32) NOT NULL,
  [LIBELLE_PRM] [varchar](1000) NOT NULL,
  [BASE_PRM] [money] NOT NULL,
  [TAUX_DE_PRM] [smallint] NOT NULL,
  [GAINS_PRM] [money] NOT NULL,
  CONSTRAINT [PK_PRIME] PRIMARY KEY CLUSTERED ([CODE_PRM])
)
ON [PRIMARY]
GO