CREATE TABLE [dbo].[Groupe] (
  [CODE] [varchar](50) NOT NULL,
  [FL] [varchar](50) NOT NULL,
  CONSTRAINT [PK_Groupe] PRIMARY KEY CLUSTERED ([CODE])
)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[Groupe]
  ADD CONSTRAINT [FK_Groupe_FILERE] FOREIGN KEY ([FL]) REFERENCES [dbo].[FILERE] ([CODE])
GO