CREATE TABLE [dbo].[AVANTAGE] (
  [CODE_AVG] [char](32) NOT NULL,
  [LIBELLE_AVG] [varchar](1000) NOT NULL,
  [GAINS_AVG] [money] NOT NULL,
  CONSTRAINT [PK_AVANTAGE] PRIMARY KEY CLUSTERED ([CODE_AVG])
)
ON [PRIMARY]
GO