CREATE TABLE [dbo].[COTISATION_PERSONNEL] (
  [CODE_COT_PRS] [char](32) NOT NULL,
  [LIBELLE_COT_PRS] [varchar](1000) NOT NULL,
  [AVANCE] [money] NOT NULL,
  [OPPOSITION] [money] NOT NULL,
  [RETENUS_COT_PRS] [money] NOT NULL,
  CONSTRAINT [PK_COTISATION_PERSONNEL] PRIMARY KEY CLUSTERED ([CODE_COT_PRS])
)
ON [PRIMARY]
GO